all:
  children:
    dmz:
      hosts:
        dmz-vm:
          ansible_host: 10.0.2.10
          ansible_user: vagrant
          ansible_ssh_private_key_file: ../.vagrant/machines/dmz/virtualbox/private_key
    internal:
      hosts:
        internal-vm:
          ansible_host: 10.0.1.11
          ansible_user: vagrant
          ansible_ssh_private_key_file: ../.vagrant/machines/internal/virtualbox/private_key
    mgmt:
      hosts:
        mgmt-vm:
          ansible_host: 10.0.3.10
          ansible_user: vagrant
          ansible_ssh_private_key_file: ../.vagrant/machines/mgmt/virtualbox/private_key
