all:
  children:
    dmz:
      hosts:
        dmz-vm:
          ansible_host: '{{ lookup("env", "D2_DMZ_HOST") | default("10.0.2.10", true) }}'
          ansible_user: '{{ lookup("env", "D2_VM_SSH_USER") | default("vagrant", true) }}'
          ansible_ssh_private_key_file: '{{ lookup("env", "D2_DMZ_KEY_PATH") | default("../../.vagrant/machines/dmz/virtualbox/private_key", true) }}'
    internal:
      hosts:
        internal-vm:
          ansible_host: '{{ lookup("env", "D2_INTERNAL_HOST") | default("10.0.1.11", true) }}'
          ansible_user: '{{ lookup("env", "D2_VM_SSH_USER") | default("vagrant", true) }}'
          ansible_ssh_private_key_file: '{{ lookup("env", "D2_INTERNAL_KEY_PATH") | default("../../.vagrant/machines/internal/virtualbox/private_key", true) }}'
    mgmt:
      hosts:
        mgmt-vm:
          ansible_host: '{{ lookup("env", "D2_MGMT_HOST") | default("10.0.3.10", true) }}'
          ansible_user: '{{ lookup("env", "D2_VM_SSH_USER") | default("vagrant", true) }}'
          ansible_ssh_private_key_file: '{{ lookup("env", "D2_MGMT_KEY_PATH") | default("../../.vagrant/machines/mgmt/virtualbox/private_key", true) }}'
