location /api/documents/ {
  auth_request /_opa_auth;
  error_page 401 = @auth_unauthorized;
  error_page 403 = @auth_forbidden;
  proxy_pass https://storage_up;
  include /etc/nginx/conf.d/proxy_mtls_storage.conf;
  proxy_set_header Host $host;
}

location /api/pki/certificates {
  auth_request /_opa_auth;
  error_page 401 = @auth_unauthorized;
  error_page 403 = @auth_forbidden;
  proxy_pass https://storage_up;
  include /etc/nginx/conf.d/proxy_mtls_storage.conf;
  proxy_set_header Host $host;
}

location /api/pki/ {
  auth_request /_opa_auth;
  error_page 401 = @auth_unauthorized;
  error_page 403 = @auth_forbidden;
  proxy_pass https://doc_up;
  include /etc/nginx/conf.d/proxy_mtls_doc.conf;
  proxy_set_header Host $host;
}

location /api/qr/ {
  auth_request /_opa_auth;
  error_page 401 = @auth_unauthorized;
  error_page 403 = @auth_forbidden;
  proxy_pass https://qr_up;
  include /etc/nginx/conf.d/proxy_mtls_qr.conf;
  proxy_set_header Host $host;
}

location /doc/ {
  auth_request /_opa_auth;
  error_page 401 = @auth_unauthorized;
  error_page 403 = @auth_forbidden;
  proxy_pass https://doc_up;
  include /etc/nginx/conf.d/proxy_mtls_doc.conf;
  proxy_set_header Host $host;
}

location = /health {
  proxy_pass https://storage_up;
  include /etc/nginx/conf.d/proxy_mtls_storage.conf;
  proxy_set_header Host $host;
}
