location = /api/storage/login {
  proxy_pass https://storage_up;
  include /etc/nginx/conf.d/proxy_mtls_storage.conf;
  proxy_set_header Host $host;
}

location = /api/storage/officers/login {
  proxy_pass https://storage_up;
  include /etc/nginx/conf.d/proxy_mtls_storage.conf;
  proxy_set_header Host $host;
}

location = /api/storage/register {
  proxy_pass https://storage_up;
  include /etc/nginx/conf.d/proxy_mtls_storage.conf;
  proxy_set_header Host $host;
}

location = /api/storage/register/officer {
  proxy_pass https://storage_up;
  include /etc/nginx/conf.d/proxy_mtls_storage.conf;
  proxy_set_header Host $host;
}

location = /api/storage/register/thirdparty {
  proxy_pass https://storage_up;
  include /etc/nginx/conf.d/proxy_mtls_storage.conf;
  proxy_set_header Host $host;
}

location = /api/storage/qr-register {
  proxy_pass https://storage_up;
  include /etc/nginx/conf.d/proxy_mtls_storage.conf;
  proxy_set_header Host $host;
}

location = /.well-known/jwks.json {
  proxy_pass https://storage_up;
  include /etc/nginx/conf.d/proxy_mtls_storage.conf;
  proxy_set_header Host $host;
}

location /api/storage/register/ {
  proxy_pass https://storage_up;
  include /etc/nginx/conf.d/proxy_mtls_storage.conf;
  proxy_set_header Host $host;
}
