proxy_ssl_certificate     /etc/nginx/mtls/gateway/client.crt;
proxy_ssl_certificate_key /etc/nginx/mtls/gateway/client.key;
proxy_ssl_trusted_certificate /etc/nginx/mtls/ca/ca.crt;
proxy_ssl_verify on;
proxy_ssl_verify_depth 2;
proxy_ssl_server_name on;
proxy_ssl_name storage_service.govportal.local;
include /etc/nginx/conf.d/proxy_hide_cors.conf;
proxy_set_header X-Client-Cert-Verify $http_x_client_cert_verify;
proxy_set_header X-Client-Cert-Subject $http_x_client_cert_subject;
proxy_set_header X-Client-Cert-Issuer $http_x_client_cert_issuer;
proxy_set_header X-Client-Cert-Fingerprint $http_x_client_cert_fingerprint;
