events {}
http {
  upstream doc_up {
    server doc_service:5000;
  }
  upstream storage_up {
    server storage_service:9003;
  }
  upstream qr_up {
    server qr_service:5002;
  }

  server {
    listen 80;

    location /api/documents/ {
      proxy_pass http://doc_up;
      proxy_set_header Host $host;
    }

    location /api/pki/ {
      proxy_pass http://doc_up;
      proxy_set_header Host $host;
    }

    location /api/storage/ {
      proxy_pass http://storage_up;
      proxy_set_header Host $host;
    }

    location /api/thirdparty/ {
      proxy_pass http://storage_up;
      proxy_set_header Host $host;
    }

    location /api/qr/ {
      proxy_pass http://qr_up;
      proxy_set_header Host $host;
    }

    location /doc/ {
      proxy_pass http://doc_up;
      proxy_set_header Host $host;
    }

    location /storage/ {
      proxy_pass http://storage_up;
      proxy_set_header Host $host;
    }
  }
}
