proxy_ssl_certificate     /etc/nginx/mtls/gateway/client.crt;
proxy_ssl_certificate_key /etc/nginx/mtls/gateway/client.key;
proxy_ssl_trusted_certificate /etc/nginx/mtls/ca/ca.crt;
proxy_ssl_verify on;
proxy_ssl_verify_depth 2;
proxy_ssl_server_name on;
proxy_ssl_name doc_service.govportal.local;
include /etc/nginx/conf.d/proxy_hide_cors.conf;
