location /api/storage/ {
  auth_request /_opa_auth;
  error_page 401 = @auth_unauthorized;
  error_page 403 = @auth_forbidden;
  proxy_pass https://storage_up;
  include /etc/nginx/conf.d/proxy_mtls_storage.conf;
  proxy_set_header Host $host;
}

location /api/thirdparty/ {
  auth_request /_opa_auth;
  error_page 401 = @auth_unauthorized;
  error_page 403 = @auth_forbidden;
  proxy_pass https://storage_up;
  include /etc/nginx/conf.d/proxy_mtls_storage.conf;
  proxy_set_header Host $host;
}

location /storage/ {
  auth_request /_opa_auth;
  error_page 401 = @auth_unauthorized;
  error_page 403 = @auth_forbidden;
  proxy_pass https://storage_up;
  include /etc/nginx/conf.d/proxy_mtls_storage.conf;
  proxy_set_header Host $host;
}
