Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu/jammy64'
 
  # VM-DMZ: NGINX Gateway
  config.vm.define 'dmz' do |m|
    m.vm.hostname = 'dmz'
    m.vm.network 'private_network', ip: '10.0.2.10'
    m.vm.network 'private_network', ip: '10.0.1.10',
                 virtualbox__intnet: 'internal-net'
    m.vm.provider 'virtualbox' do |v|
      v.name = 'govportal-dmz'
      v.memory = 1024; v.cpus = 1
    end
  end
 
  # VM-Internal: Keycloak + OPA + Services
  config.vm.define 'internal' do |m|
    m.vm.hostname = 'internal'
    m.vm.network 'private_network', ip: '10.0.1.11',
                 virtualbox__intnet: 'internal-net'
    m.vm.network 'private_network', ip: '10.0.3.11',
                 virtualbox__intnet: 'mgmt-net'
    m.vm.provider 'virtualbox' do |v|
      v.name = 'govportal-internal'
      v.memory = 2048; v.cpus = 2
    end
  end
 
  # VM-Mgmt: Vault KMS + Internal CA
  config.vm.define 'mgmt' do |m|
    m.vm.hostname = 'mgmt'
    m.vm.network 'private_network', ip: '10.0.3.10',
                 virtualbox__intnet: 'mgmt-net'
    m.vm.provider 'virtualbox' do |v|
      v.name = 'govportal-mgmt'
      v.memory = 1024; v.cpus = 1
    end
  end
end
