Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu/jammy64'

  # VM-DMZ
  config.vm.define 'dmz' do |m|
    m.vm.hostname = 'dmz'
    m.vm.network 'private_network', ip: '10.0.2.10'
    m.vm.provider 'virtualbox' do |v|
      v.memory = 1024
    end
  end

  # VM-Internal
  config.vm.define 'internal' do |m|
    m.vm.hostname = 'internal'
    m.vm.network 'private_network', ip: '10.0.1.11'
    m.vm.provider 'virtualbox' do |v|
      v.memory = 2048
    end
  end

  # VM-Mgmt
  config.vm.define 'mgmt' do |m|
    m.vm.hostname = 'mgmt'
    m.vm.network 'private_network', ip: '10.0.3.10'
    m.vm.provider 'virtualbox' do |v|
      v.memory = 1024
    end
  end
end
