Vagrant.configure('2') do |config|
  dmz_host_ip = ENV.fetch('D2_DMZ_HOST', '10.0.2.10')
  dmz_internal_ip = ENV.fetch('D2_DMZ_INTERNAL_HOST', '10.0.1.10')
  internal_host_ip = ENV.fetch('D2_INTERNAL_HOST', '10.0.1.11')
  internal_mgmt_ip = ENV.fetch('D2_INTERNAL_MGMT_HOST', '10.0.3.11')
  mgmt_host_ip = ENV.fetch('D2_MGMT_HOST', '10.0.3.10')

  dmz_memory = ENV.fetch('D2_DMZ_MEMORY', '1024').to_i
  dmz_cpus = ENV.fetch('D2_DMZ_CPUS', '1').to_i
  internal_memory = ENV.fetch('D2_INTERNAL_MEMORY', '2048').to_i
  internal_cpus = ENV.fetch('D2_INTERNAL_CPUS', '2').to_i
  mgmt_memory = ENV.fetch('D2_MGMT_MEMORY', '1024').to_i
  mgmt_cpus = ENV.fetch('D2_MGMT_CPUS', '1').to_i

  config.vm.box = 'ubuntu/jammy64'
 
  # VM-DMZ: NGINX Gateway
  config.vm.define 'dmz' do |m|
    m.vm.hostname = 'dmz'
    m.vm.network 'private_network', ip: dmz_host_ip
    m.vm.network 'private_network', ip: dmz_internal_ip,
                 virtualbox__intnet: 'internal-net'
    m.vm.provider 'virtualbox' do |v|
      v.name = 'govportal-dmz'
      v.memory = dmz_memory; v.cpus = dmz_cpus
    end
  end
 
  # VM-Internal: Keycloak + OPA + Services
  config.vm.define 'internal' do |m|
    m.vm.hostname = 'internal'
    m.vm.network 'private_network', ip: internal_host_ip,
                 virtualbox__intnet: 'internal-net'
    m.vm.network 'private_network', ip: internal_mgmt_ip,
                 virtualbox__intnet: 'mgmt-net'
    m.vm.provider 'virtualbox' do |v|
      v.name = 'govportal-internal'
      v.memory = internal_memory; v.cpus = internal_cpus
    end
  end
 
  # VM-Mgmt: Vault KMS + Internal CA
  config.vm.define 'mgmt' do |m|
    m.vm.hostname = 'mgmt'
    m.vm.network 'private_network', ip: mgmt_host_ip,
                 virtualbox__intnet: 'mgmt-net'
    m.vm.provider 'virtualbox' do |v|
      v.name = 'govportal-mgmt'
      v.memory = mgmt_memory; v.cpus = mgmt_cpus
    end
  end
end
